password_manager_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('<str:tag>', views.get_tag, name='tags'),
]

password_manager_django/urls.py
from django.contrib import admin
from django.urls import path, include
from password_manager_app import views

admin.site.site_header = 'Админ панель'
admin.site.index_title = 'Менеджер паролей'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('search/', views.index, name='search_results'),
    path('tag/', include('password_manager_app.urls')),
    path('new_post/', views.new_post, name='new_post'),
    path('edit_post/<str:post_slug>', views.edit_post, name='edit_post'),
    path('delete_post/<str:post_slug>', views.delete_post, name='delete_post'),
    path('users/', include('users.urls'))
]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls'))
]

password_manager_app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from encrypted_model_fields.fields import EncryptedCharField


class Tag(models.Model):

    name = models.CharField(max_length=100, null=False, default='')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='URL')

    def __str__(self):
        return f'{self.name}'


    def get_url(self):
        return reverse('tags', args=[self.slug])


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)


# class New_tags(TagModel):
#     class TagMeta:
#         # Tag options
#         initial = "tag1, tag2, tag3"
#         force_lowercase = True
#         # autocomplete_view = 'myapp.views.hobbies_autocomplete'

class PasswordManager(models.Model):

    resource_name = models.CharField(max_length=100, blank=True, default='')
    resource_name_alias = models.CharField(max_length=100, blank=True, default='')
    esia_login = models.BooleanField(default=False)
    ip = models.CharField(max_length=100, null=True, blank=False)
    login = models.CharField(max_length=100, null=False, blank=True)
    password = EncryptedCharField(max_length=100)
    tags = models.ManyToManyField(Tag, blank=True)
    # tags = TagField(to=New_tags)
    post_slug = models.SlugField(max_length=100, unique=False, default='dflt')
    post_time = models.DateTimeField(auto_now=True)
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.ip}'


    def get_url(self):
        return reverse('edit_post', args=[self.post_slug,])


    def save(self, *args, **kwargs):
        self.post_slug = f'{slugify(self.ip)}_{self.login}'
        self.resource_name_alias = str(self.resource_name).lower()
        super(PasswordManager, self).save(*args, **kwargs)



'''Перезаписать данные после миграции'''
# for item in PasswordManager.objects.all():
#     item.save()

password_manager_app/forms.py
from django import forms
from .models import PasswordManager, Tag
from django.contrib.auth.models import User


class PasswordManagerForm(forms.ModelForm):

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label='Выберите теги'
    )

    # post_author = forms.CharField(max_length=100, disabled=False)

    class Meta:
        model = PasswordManager
        exclude = ("post_author",)
        fields = ['resource_name', 'ip', 'login', 'password', 'esia_login', 'tags']
        labels = {
            'resource_name': 'Названние ресурса',
            'ip': 'Адрес ресурса',
            'login': 'Логин',
            'esia_login': 'Вход через Госуслуги',
            'password': 'Пароль',
            'tags': 'Выберите теги',
        }

    # def save(self, commit=True):
    #     instance = super(PasswordManagerForm, self).save(commit=False)
    #     instance.post_author = User.objects.get(id=post_author)
    #     if commit:
    #         instance.save()
    #     return instance

password_manager_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound
from password_manager_app.models import PasswordManager, Tag
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import PasswordManagerForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


kirill = ('абвгдеёжзийклмнопрстуфхцчшщъыьэюя')
kirill = kirill + kirill.upper()

@login_required
def index(request):
    search_query = request.GET.get('q', '')
    for letter in search_query:
        if letter in kirill:
            search_query = search_query.lower()
            break
    if search_query:
        pass_list = PasswordManager.objects.filter(
            (Q(ip__icontains=search_query) |
            Q(login__icontains=search_query) |
            Q(resource_name_alias__icontains=search_query)) &
            Q(post_author=request.user)
        )
    else:
        pass_list = PasswordManager.objects.filter(post_author=request.user).order_by('-id')
    tags_list = Tag.objects.order_by('name')
    context = {
        'pass_list': pass_list,
        'tags_list': tags_list
    }
    return render(request, 'password_manager_app/manager.html', context=context)


@login_required
def get_tag(request, tag):
    tagname = get_object_or_404(Tag, slug=tag)
    pass_list = PasswordManager.objects.filter(post_author=request.user).order_by('-id')
    tags_list = Tag.objects.order_by('name')
    context = {
        'pass_list': pass_list,
        'tags_list': tags_list,
        'tagname': tagname,
    }
    return render(request, 'password_manager_app/selected.html', context=context)


@login_required
def new_post(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = PasswordManagerForm()
    else:
        # Отправлены данные POST; обработать данные.
        userid = request.user
        form = PasswordManagerForm(data=request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.post_author = userid
            form.save()
        return redirect('index')
    context = {
        'form': form,
    }
    return render(request, 'password_manager_app/new_post.html', context)


@login_required
def edit_post(request, post_slug):
    """Редактирует существующую запись."""
    post = get_object_or_404(PasswordManager, post_slug=post_slug)
    name = post.post_author
    if post.post_author != request.user:
        raise Http404
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = PasswordManagerForm(instance=post)
    else:
        # Отправлены данные POST; обработать данные.
        form = PasswordManagerForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
        return redirect('index')
    return render(request, 'password_manager_app/post_page.html', context={'post': post, 'form':form})


@login_required
def delete_post(request, post_slug):
    post = get_object_or_404(PasswordManager, post_slug=post_slug)
    if request.method != 'POST':
        form = PasswordManagerForm(instance=post)
    else:
        form = PasswordManagerForm(instance=post, data=request.POST)
        post.delete()
        # return redirect('index')
        return render(request, 'password_manager_app/del_post.html', context={'post': post, 'form': form})
    # return render(request, 'password_manager_app/del_post.html', context={'post': post, 'form':form})
    return redirect('index')

password_manager_app/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Password<span style="font-weight:bold">Manager</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                {% if user.is_authenticated %}
                <span class="nav-link" style="font-size: 18px !important;" >Привет, {{ user.username }}</span>
                {% else %}
                <a class="nav-link" aria-current="page" href="{% url 'users:login' %}">Войти</a>
                {% endif %}
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'new_post' %}">Добавить запись</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

password_manager_app/templates/password_manager_app/manager.html
{% extends 'base.html' %}

{% load static %}

{% load tz %}



{% block content %}
{% if user.is_authenticated %}
<h2>Список паролей</h2>
<div class="table-responsive">
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Имя ресурса</th>
            <th scope="col">Адрес ресурса</th>
            <th scope="col">Логин</th>
            <th scope="col" style="width: 250px;">Пароль </div></th>
        </tr>
    </thead>
    <tbody>
        {% for pass in pass_list %}
            <tr>
                <td>
                    {% if pass.resource_name %}
                    <strong>{{ pass.resource_name }}</strong><br>
                    {% else %}
                    <strong>{{ pass.ip }}</strong><br>
                    {% endif %}
                    {% timezone "Europe/Moscow" %}
                    <span style="font-size: 11px;">{{ pass.post_time|date:"d M Y H i" }}</span>
                    {% endtimezone %}
                </td>
                <td><a href="{{ pass.get_url }}">
                    <img src="{% static 'img/pencil-square.svg' %}" alt="edit" srcset="" style="width: 13px; margin-right: 5px;"></a>{{ pass.ip }}
                    {% if pass.esia_login %}
                    <img src="{% static 'img/goslogo.png' %}" alt="gosuslugi" style="width:50px">
                    {% endif %}
                    <br>
                    {% for tag in pass.tags.all %}
                    <a href="{{ tag.get_url }}"><span class="badge badge-primary">{{ tag }}</span></a>
                    {% endfor %}
                </td>
                <td>{{ pass.login }}</td>
                <td>
                        <div class="row">
                            <div class="passwords col-md-8" id="{{ pass.login }}"><p>{{ pass.password }}</p></div>
                            <a class="content_toggle col-md-2" data-target="#{{ pass.login }}" href=""><img src="{% static 'img/eye-fill.svg' %}"></a>
                            <a  class='col-md-2' href="" id='copy' onclick="copytext('#{{ pass.login }}')"><img src="{% static 'img/clipboard-fill.svg' %}" alt="" srcset=""></a>
                        </div>
                    
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% else %}
<div class="attention col-md-6">
    <h2>Вы не авторизованы</h2>
    <a href="{% url 'users:login' %}"><button class="btn btn-primary" type="submit">Авторизоваться</button></a>
</div>
{% endif %}
{% endblock %}

{% block tags %}
{% if user.is_authenticated %}
    <h2>Список тегов</h2>
    <ul>
    {% for tag in tags_list %}
        <li><a href="{{ tag.get_url }}">{{ tag.name }}</a> <span class="badge badge-primary">{{ tag.passwordmanager_set.count }}</span></li>
    {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

password_manager_app/templates/password_manager_app/new_post.html
{% extends 'base.html' %}

{% block title %}<title>Добавление записи</title>{% endblock %}

{% load crispy_forms_tags %}

{% block top %}
<h2 style="text-align: center; margin: 20px;">Добавление записи</h2>

<div class="login-form">
    <form action="{% url 'new_post' %}" method='post'>
    
        {% csrf_token %}
    
        <div class="row login-form">
            <div class="col-md-3">
                {{ form.resource_name|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.ip|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.login|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.password|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.esia_login|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.tags|as_crispy_field }}
                <div class="invisible">{{ form.post_author }}</div>
            </div>
        </div>
        <button name="submit" class="btn btn-primary">Добавить запись</button>
        <hr>
        * - обязательно к заполнению
    </form>
    </div>

{% endblock %}

{% block content %}

{% endblock %}

{% block tags %}

{% endblock %}

password_manager_app/templates/password_manager_app/post_page.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}<title>{{ post.ip }}</title>{% endblock %}

{% block top %}

<h2 style="text-align: center; margin: 20px;">Редактировать запись {{ post.ip }}</h2>

    <div class="login-form">

    <form action="{% url 'edit_post' post.post_slug %}" method='post'>

    {% csrf_token %}

    <div class="row">
        <div class="col-md-3">
            {{ form.resource_name|as_crispy_field }}
        </div>
        <div class="col-md-3">
            {{ form.ip|as_crispy_field }}
        </div>
        <div class="col-md-3">
            {{ form.login|as_crispy_field }}
        </div>
        <div class="col-md-3">
            {{ form.password|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ form.esia_login|as_crispy_field }}
        </div>
        <div class="col-md-6">
            {{ form.tags|as_crispy_field }}
        </div>
    </div>
    <button name="submit" class="btn btn-primary">Изменить запись</button>
    <hr>
</form>
<form action="{% url 'delete_post' post.post_slug %}" method="post">
    {% csrf_token %}
    <button name="submit" class="btn btn-danger">Удалить запись</button>
</form>
</div>

{% endblock %}

{% block content %}
    
{% endblock %}

password_manager_app/templates/password_manager_app/selected.html
{% extends 'base.html' %}

{% load static %}

{% load tz %}

{% block content %}
<h2>Список паролей</h2>
<h4>{{ tagname }}</h4>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Имя ресурса</th>
                <th scope="col">Адрес ресурса</th>
                <th scope="col">Логин</th>
                <th scope="col" style="width: 250px;">Пароль</th>
            </tr>
        </thead>
        <tbody>
            {% for pass in tagname.passwordmanager_set.all %}
                <tr>{% if user == pass.post_author %}
                    <td>
                        {% if pass.resource_name %}
                        <strong>{{ pass.resource_name }}</strong><br>
                        {% else %}
                        <strong>{{ pass.ip }}</strong><br>
                        {% endif %}
                        {% timezone "Europe/Moscow" %}
                        <span style="font-size: 11px;">{{ pass.post_time|date:"d M Y H i" }}</span>
                        {% endtimezone %}
                        {{pass.post_author}}
                    </td>
                    <td><a href="{{ pass.get_url }}">
                        <img src="{% static 'img/pencil-square.svg' %}" alt="edit" srcset="" style="width: 13px; margin-right: 5px;"></a>{{ pass.ip }}
                        {% if pass.esia_login %}
                        <img src="{% static 'img/goslogo.png' %}" alt="gosuslugi" style="width:50px">
                        {% endif %}
                        <br>
                    {% for tag in pass.tags.all %}
                    <a href="{{ tag.get_url }}"><span class="badge badge-primary">{{ tag }}</span></a>
                    {% endfor %}
                    </td>
                    <td>{{ pass.login }}</td>
                    <td>
                        <div class="row">
                            <div class="passwords col-md-8" id="{{ pass.login }}"><p>{{ pass.password }}</p></div>
                            <a class="content_toggle col-md-2" data-target="#{{ pass.login }}" href=""><img src="{% static 'img/eye-fill.svg' %}"></a>
                            <a  class='col-md-2' href="" id='copy' onclick="copytext('#{{ pass.login }}')"><img src="{% static 'img/clipboard-fill.svg' %}" alt="" srcset=""></a>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                
            {% endfor %}
            
        </tbody>
    </table>
</div>

{% endblock %}

{% block tags %}
    <h2>Список тегов</h2>
    <ul>
    {% for tag in tags_list %}
    <li><a href="{{ tag.get_url }}">{{ tag.name }}</a> <span class="badge badge-primary">{{ tag.passwordmanager_set.count }}</span></li>
    {% endfor %}
    </ul>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css_add %}
    {% endblock %}
    {% block head_add %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favv.png' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="{% static 'js/switcher.js' %}"></script>
    <script src="{% static 'js/copy.js' %}"></script>
    <script src="{% static 'js/one_pass_switch.js' %}"></script>
    {% block title %}<title>Менеджер Паролей</title>{% endblock %}
</head>
<body>
{% include 'includes/navbar.html' %}
{% if user.is_authenticated %}
    <div class="container">
        <div class="top" style="margin: 20px 0;">
            <h1>Менеджер Паролей</h1>
        <div class="search col-xs-12" style="display:flex; justify-content: center; margin-top: 25px;">
            <form class="d-flex col-md-6 col-xs-12" action="{% url 'search_results' %}" method="get">
                <input name="q" class="form-control col-xs-12 me-2" type="search" placeholder="Адрес ресурса или Логин" aria-label="Search">
                <button class="btn btn-warning" type="submit">Искать</button>
            </form>
        </div>
        </div>
{% endif %}
{% block top %}
<div class="row">
    <div class="col-md-12">
        
    </div>
</div> 
{% endblock %}
        <div class="row">
            <div class="col-md-3 left">
                {% block tags %} 
                {% endblock %}
            </div>
            <div class="col-md-9 right">
                {% block content %} 
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>